version: '3.5'
networks:
  car_app_net:
services:
  car_app:
    build:
      context: .
    networks:
      - car_app_net
    ports:
      - 3000:5000
    volumes:
      - .:/usr/src/app
    command: ["npm","start"]
    environment:
      - PORT=5000
      - MONGO_PASSWORD=Qwerty
      - CONNECTION_STRING=mongodb+srv://admin:<PASSWORD>@inventory-bzl5t.mongodb.net/test?retryWrites=true&w=majority  